const educationData = [
  {
    title: "Licenciatura en desarrollo de software",
    institution: "Brigham Young University–Idaho",
    location: "Rexburg, Idaho, U.S.A.",
    startDate: "Marzo 2023",
    endDate: "presente",
    details: [
      "Aprender y aplicar nuevas tecnologías y técnicas",
      "Use Python, HTML/CSS, C#, and JavaScript",
      "Convertir requisitos de software en código",
      "Comprender los principios de programación y diseño",
      "Aplicar habilidades sólidas de diseño y resolución de problemas",
      "Fuertes habilidades de comunicación e interpersonales",
    ],
    certificateUrl: null,
  },
  {
    title: "Certificado de PathwayConnect",
    institution: "BYU–Pathway Worldwide",
    location: "U.S.A.",
    startDate: "Marzo 2022",
    endDate: "Noviembre 2022",
    details: [
      "Hablar y escribir en inglés",
      "Trabajo en equipo y colaboración en línea",
      "Liderazgo y gestión del tiempo",
      "Toma de decisiones y resolución de problemas",
      "Razonamiento matemático",
      "Comunicación efectiva",
    ],
    certificateUrl: null,
  },
  // {
  //   title: "Desarrollo Full Stack",
  //   institution: "Coderhouse",
  //   location: "Buenos Aires, Argentina",
  //   startDate: "Marzo 2023",
  //   endDate: "presente",
  //   details: [
  //     "Desarrollo web: HTML, CSS",
  //     "JavaScript",
  //     "React JS",
  //     "Backend: MERN",
  //   ],
  //   certificateUrl: null,
  // },
  {
    title: "Python",
    institution: "Coderhouse",
    location: "Buenos Aires, Argentina",
    startDate: "Enero 2023",
    endDate: "Abril 2023",
    details: [
      "Utilizar entornos virtuales con Pipenv para gestionar cómodamente proyectos",
      "Aplicar Django Framework y su MVT basado en Modelos, Vistas y Templates",
      "Crear backends con panel administrable, listos para darles un uso real",
      "Utilizar CBV, las Vistas Basadas en Clases",
      "Gestionar usuarios, autenticación, registro y perfiles utilizando los módulos nativos de Django",
      "Guiar el desarrollo basado en pruebas TDD (Test Driven Development)",
      "Incorporar docenas de funcionalidades más a un proyecto: Tags, Contextos, Formularios, Mixins, CRUD, Paginación, Señales, Managers, Test",
    ],
    certificateUrl: null,
  },
  {
    title: "Desarrollo de aplicaciones",
    institution: "Coderhouse",
    location: "Buenos Aires, Argentina",
    startDate: "Octubre 2022",
    endDate: "Enero 2023",
    details: [
      "Diseñar un wireframe como guía visual para representar el flujo de una aplicación",
      "Definir las funcionalidades requeridas y el alcance de las librerías externas para sacar provecho de las capacidades del dispositivo",
      "Crear aplicaciones móviles de tipo bridge, capaces de ser desplegadas en iOS y Android.",
    ],
    certificateUrl: null,
  },
  {
    title: "Programación Backend",
    institution: "Coderhouse",
    location: "Buenos Aires, Argentina",
    startDate: "Enero 2023",
    endDate: "Julio 2023",
    details: [
      "Comprender el ecosistema Node.js/JavaScript",
      "Dominar los lenguajes JavaScript JS5, ES6, ES7, ES8, ES9, ES10, ES11",
      "Programar en Javascript asincrónico avanzado del lado del servidor",
      "Utilizar framework Express",
      "Usar el framework Handlebars para manejar plantillas HTML",
      "Crear APIs con RESTFul",
      "Dominar la tecnología Websockets",
      "Hacer la instalación de MongoDB",
      "Comprender los principios SQL y sus diferencias con MongoDB",
      "Trabajar con la consola de MongoDB y clientes UI/Web",
      "Manejar MongoDB desde Node.js a través de Mongoose",
      "Realizar CRUD con MongoDB",
      "Normalizar/denormalizar datos en formato JSON",
      "Implementar proyectos en la nube a través de plataformas como, Heroku, Glitch, MongoAtlas",
      "Utilizar framework Express",
      "Utilizar mongoose",
      "Implementar sistemas de autenticación y autorización",
      "Usar el framework Handlebars para manejar plantillas HTML",
      "Crear APIs con RESTFul",
      "Testear y monitorear aplicaciones REST",
      "Normalizar/denormalizar datos en formato JSON",
      "Manejar patrones de diseño y code style para aplicaciones de alta concurrencia",
      "Diseñar servidores web desarrollando en capas con MVC",
      "Realizar pruebas exhaustivas y monitoreo de aplicaciones REST",
      "Implementar estrategias de optimización, incluyendo normalización, Gzip y manejo de logs",
      "Manejar la gestión de versiones y paquetes en entornos Node.js",
      "Configurar y asegurar aplicaciones, enfocándote en la seguridad del backend",
      "Desarrollar pruebas unitarias y pruebas avanzadas de funcionalidades",
      "Utilizar y comprender el funcionamiento de Clusters para la escalabilidad",
      "Aplicar prácticas de desarrollo con frameworks como NEST",
      "Documentar APIs REST de manera efectiva",
      "Desplegar y administrar aplicaciones en entornos en la nube, incluyendo product cloud environments",
    ],
    certificateUrl: null,
  },
  {
    title: "React Js",
    institution: "Coderhouse",
    location: "Buenos Aires, Argentina",
    startDate: "Enero 2022",
    endDate: "Febrero 2022",
    details: [
      "Crear desde cero SPA, haciendo foco en las interfaces de usuario",
      "Desarrollar aplicaciones web en Javascript utilizando ReactJS, la librería de código abierto con mayor crecimiento en la web",
      "Diseñar soluciones web rápidas, escalables, flexibles y potentes",
    ],
    certificateUrl:
      "https://www.coderhouse.com/ar/certificados/622542c9fbd8de0024d6e456?lang=es",
  },
  {
    title: "JavaScript",
    institution: "Coderhouse",
    location: "Buenos Aires, Argentina",
    startDate: "Abril 2022",
    endDate: "Junio 2022",
    details: [
      "Consolidar un perfil técnico en desarrollo de software interactivo, especializado en sitios y aplicaciones web y su comunicación con el backend y/o servicios de terceros.",
    ],
    certificateUrl:
      "https://www.coderhouse.com/ar/certificados/62b5b172b0ad99001b533e1b?lang=es",
  },
  {
    title: "Desarrollo Web",
    institution: "Coderhouse",
    location: "Buenos Aires, Argentina",
    startDate: "Septiembre 2021",
    endDate: "Diciembre 2021",
    details: [
      "Introducción al Desarrollo Web",
      "Prototipado y conceptos básicos de HTML",
      "Primeros pasos con HTML",
      "CSS + Box Modeling",
      "Flexbox",
      "GRID",
      "Animaciones, transformaciones y transiciones",
      "GIT y Github",
      "Frameworks CSS + Bootstrap",
      "Media queries + pseudoclases",
      "SASS",
      "Servidores y SEO",
      "Subida al servidor",
    ],
    certificateUrl:
      "https://www.coderhouse.com/ar/certificados/61bca0a24e461300347cf1ab?lang=es",
  },
];

export { educationData };
